language: erlang

otp_release:
 - 17.4
 - 17.3

env:
 - TASK=lint
 - TASK=dialyzer
 - TASK=unit-tests
 - TASK=validate-examples
 - TASK=error-messages
 - TASK=acceptance-local-tests
 - TASK=acceptance-basic-tests
 - TASK=development-with-rsync
 - TASK=acceptance-signal-tests
 - TASK=acceptance-negative-tests
 - TASK=http-worker-tests

matrix:
 exclude:
  - otp_release: 17.3
    env: TASK=lint

script:
 - export PROJECTS="node server common_apps/mzbench_language common_apps/mzbench_utils";
 - case "$TASK" in
     lint) sudo pip install --src pip_src -r requirements.txt && sudo rm -rf pip_src && sudo pip install pyflakes && ./bin/lint.py . ;;
     validate-examples) sudo pip install -r requirements.txt && make -C examples check;;
     error-messages) sudo pip install -r requirements.txt && make -C acceptance_tests/invalid_scripts check;;
     http-worker-tests) sudo pip install -r requirements.txt &&
                       export NODE_COMMIT=`git rev-parse HEAD` &&
                       export MZBENCH_REPO=`pwd` &&
                       cd workers/http &&
                       make && make check-local;;
     acceptance-*-tests) sudo pip install -r requirements.txt &&
                       sudo pip install -r acceptance_tests/requirements.txt &&
                       export NODE_COMMIT=`git rev-parse HEAD` &&
                       export MZBENCH_REPO=`pwd` &&
                       cd acceptance_tests &&
                       make ${TASK/acceptance-/};;
     development-with-rsync) sudo pip install -r requirements.txt &&
                       sudo pip install -r acceptance_tests/requirements.txt &&
                       export MZBENCH_RSYNC=$PWD/ &&
                       rm node/Makefile &&
                       make -C acceptance_tests signal-tests >/dev/null; [ $? -ne 0 ] &&
                       git checkout -- node/Makefile &&
                       make -C acceptance_tests signal-tests;;
     unit-tests) for prj in $(echo $PROJECTS); do make -C $prj test-unit || exit 1; done;;
     dialyzer) for prj in $(echo $PROJECTS); do make -C $prj dialyzer.log || exit 1; done;;
   esac
